export const techStacks = [
  'Javascript',
  'Typescript',
  'React.js',
  'Next.js',
  'Express.js',
  'NestJS',
  'ASP.NET Core',
  'EF Core',
  'Git & Github',
  'Tailwind CSS',
  'Chakra UI',
  'Prisma',
  'PostgreSQL',
  'MongoDB',
];
